# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97c3bfb31716b3f5d90aa809a470727edb0df56c23fa15672902f9f72316298cf2913fa3cc40afe18e7b3a2f7b2d2bda2933c1d231ea3be647bd5a0616488cd4

test:
  secret_key_base: c87bccd2b8cf2ed9ad761d43795db72beafe0cc85e66f9b557cc24de45d327faf6ff7377017d22628aa3101bb74c01d4d97ae55790dbfda16dc6d7f18656af2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
